on: push
name: Build and Publish
jobs:
  dockerLint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Lint
      uses: docker://replicated/dockerfilelint
      with:
        args: Dockerfile
    - name: Shell Lint
      uses: actions/bin/shellcheck@master
      with:
        args: entrypoint.sh
    - name: Publish Filter
      uses: actions/bin/filter@master
      with:
        args: branch master
    - name: Build
      uses: actions/docker/cli@master
      with:
        args: build -t s3cmd-action .
    - name: Docker Login
      uses: actions/docker/login@master
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: Docker Tag
      uses: actions/docker/tag@master
      with:
        args: s3cmd-action jusbrasil/s3cmd-action --no-latest
    - name: Docker Run
      uses: actions/docker/cli@master
      with:
        args: run -t s3cmd-action
    - name: Docker Publish
      uses: actions/docker/cli@master
      with:
        args: push jusbrasil/s3cmd-action
